---
- hosts: all
  gather_facts: no
  connection: local

  vars:
     cli:
       host: "{{ inventory_hostname }}"
       username: cisco
       password: cisco
       transport: cli

  tasks:
  - name: show version of devices
    register: output
    ios_command:
      provider: "{{ cli }}"
      commands: show version
      wait_for: result[0] contains IOS
     

  - debug: msg="{{ output.stdout_lines }}"

