---
- hosts: all
  gather_facts: no
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: cisco
      password: cisco
      transport: cli

  tasks:
  - name: show interfaces
    register: output
    ios_command:
      provider: "{{ cli }}"
      commands: show interfaces
      #wait_for: result[0] contains 
     

  - debug: msg="{{ output.stdout_lines }}"
